### PR TITLE
Enable Travis CI

### PR DESCRIPTION
**Pull request by julienrf**
This PR cherry picks commits from #160 that are specific to Travis CI.

### CODE REVIEW

**Comment by julienrf** [comment]
I don’t really care about coursier. Is that really important?

**Comment by julienrf** [comment]
A more important problem for me is that the tests are failing on Travis without clear clues on the reason…

**Comment by MasseGuillaume** [comment]
@julienrf having coursier in scripted will speed up the ci time a lot.

**Comment by julienrf** [comment]
> having coursier in scripted will speed up the ci time a lot.

Why if we cache ivy’s resolutions?

**Comment by julienrf** [comment]
I just tried and didn’t really notice a performance improvement (or maybe 3%). But that’s fine…

**Comment by sjrd** [comment]
With a properly set up cache, the default ivy resolution is just fine.

I only had to resort to force coursier on Travis when I had to fetch and build all of Scala.js locally (on the Travis machine) before testing things that depended on master, because in that case the build would not even *complete* with ivy, therefore never putting things in the cache. When I did, in order not to pollute the repo everywhere with coursier setup, I did it with [these lines](https://github.com/scala-js/jsdependencies/blob/dd9a9c5365d0f85299ca69ff47d15308c4dbdf67/.travis.yml#L11-L14) and [that line](https://github.com/scala-js/jsdependencies/blob/dd9a9c5365d0f85299ca69ff47d15308c4dbdf67/.travis.yml#L43) in `.travis.yml`.

**Pull request merged**
