### PR TITLE
Fix #181: Migrate from requiresDOM to JSDOMNodeJSEnv

### LINKED ISSUE #181: deprecate requiresDOM in Test := true
Like mentioned in gitter, sbt prints:
```
 warning: value requiresDOM in object AutoImport is deprecated: Requesting a DOM-enabled JS env with `jsDependencies += RuntimeDOM` or `requiresDOM := true` will not be supported in Scala.js 1.x. Instead, explicitly select a suitable JS with `jsEnv`, e.g., `jsEnv := new org.scalajs.jsenv.jsdomnodejs.JSDOMNodeJSEnv`.
    requiresDOM in Test := true,
```

But when removing this line, the tests fail with node saying "cannot find module 'jsdom'".

### PR DESCRIPTION
**Pull request by exoego**
This PR fixes https://github.com/scalacenter/scalajs-bundler/issues/181

### CODE REVIEW

**Comment by julienrf** [comment]
I’m surprised that it works because we do rely on `scalaJSRequestsDOM` in our code: https://github.com/scalacenter/scalajs-bundler/blob/master/sbt-scalajs-bundler/src/main/scala/scalajsbundler/sbtplugin/ScalaJSBundlerPlugin.scala#L611

Maybe our test suite is not strong enough. I’ll have a deeper look on Monday.

**Comment by julienrf** [comment]
@exoego We still use `scalaJSRequestsDOM` in `ScalaJSBundlerPlugin`. We should update its usage according to these instructions:
https://github.com/scala-js/scala-js/blob/0.6.x/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPluginInternal.scala#L120-L129
(however I don’t know how we are supposed to check whether a `JSEnv` is “DOM-enabled” or not, do you have any pointer, @sjrd?)

Also, if jsdom tests turn out to work without all this machinery, then we can just remove it instead of migrating it…

**Comment by sjrd** [comment]
> however I don’t know how we are supposed to check whether a JSEnv is “DOM-enabled” or not

You cannot. I suggest you define and use a custom setting in scalajs-bundler if you need to know that.

**Comment by cquiroz** [comment]
Any chance of reviving this? I'd love to remove my 
`requiresDOM in Test`

**Comment by exoego** [comment]
I am not sure how to proceed this PR.
Any guidance is appreciated.

**Comment by ngbinh** [comment]
see https://github.com/scalacenter/scalajs-bundler/pull/266

**Comment by exoego** [comment]
So should I close this PR in favor of PR https://github.com/scalacenter/scalajs-bundler/pull/266 ?

**Comment by julienrf** [comment]
Hey, indeed I think #266 will do the job but thanks a lot for having initiated the work!

**Pull request closed without merging**
