### PR TITLE
[Experiment] Just checking the build on master

### PR DESCRIPTION
**Pull request by FabioPinheiro**

### CODE REVIEW

**Comment by FabioPinheiro** [comment]
Does anyone knows how to fix the test `.../sbt-scalajs-bundler/src/sbt-test/sbt-scalajs-bundler/webpack-assets/test`?

```
[info] [error] /tmp/sbt_36f00811/webpack-assets/target/scala-2.12/scalajs-bundler/main/node_modules/webpack-cli/bin/cli.js:74
[info] [error] 				throw err;
[info] [error] 				^
[info] [error] Error: Cannot find module 'less-loader'
[info] [error]     at Function.Module._resolveFilename (module.js:476:15)
```

**Comment by cquiroz** [comment]
webpack is trying to load `less-loader` but it is not declared as an npm dependency with something like this on `build.sbt`
```
      npmDevDependencies in Compile ++= Seq(
        "less" -> "3.9.0")
```

**Comment by FabioPinheiro** [comment]
Thanks @cquiroz
That fixed the problem. Now the next error is:
```
[info] [error] error marked@0.8.0: The engine "node" is incompatible with this module. Expected version ">= 8.16.2".
[info] [error] error Found incompatible module
```

**Comment by FabioPinheiro** [comment]
Since Travis CI had gave the green light to another PR today I happen to close this

**Comment by julienrf** [comment]
Thanks @FabioPinheiro for your investigation. I’m sorry to have stayed silent, I don’t know why I missed your PR…

**Pull request closed without merging**
