### PR TITLE
Only copy webpackResources to target dir if a webpackConfigFile is configured

### LINKED ISSUE #123: RuntimeDOM with existing webpack.config.js in a subproject crashes tests
I set up a minimal project (https://github.com/woost/wust2/tree/scalajs-bundler-subproject-bug):
```bash
git clone https://github.com/woost/wust2 -b scalajs-bundler-subproject-bug --depth=1
cd wust2
./reproduce.sh
```

What I found: the combination of jsDependencies += RuntimeDOM and an existing webpack.config.js (not specified in build.sbt) containing require('./scalajs.webpack.config') seems to break it:

```
[info] Writing and bundling the test loader
[error] module.js:471
[error]     throw err;
[error]     ^
[error] 
[error] Error: Cannot find module './scalajs.webpack.config'
[error]     at Function.Module._resolveFilename (module.js:469:15)
[error]     at Function.Module._load (module.js:417:25)
[error]     at Module.require (module.js:497:17)
[error]     at require (internal/module.js:20:19)
[error]     at Object.<anonymous> (/tmp/tmp.johz7JZIwl/wust2/frontend/target/scala-2.11/scalajs-bundler/test/webpack.config.js:1:63)
[error]     at Module._compile (module.js:570:32)
[error]     at Object.Module._extensions..js (module.js:579:10)
[error]     at Module.load (module.js:487:32)
[error]     at tryModuleLoad (module.js:446:12)
[error]     at Function.Module._load (module.js:438:3)
java.lang.RuntimeException: Non-zero exit code: 1
	at scala.sys.package$.error(package.scala:27)
	at scalajsbundler.util.Commands$.run(Commands.scala:11)
	at scalajsbundler.Webpack$.run(Webpack.scala:126)
	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$testSettings$3$$anonfun$apply$8$$anonfun$3.apply(ScalaJSBundlerPlugin.scala:632)
	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$testSettings$3$$anonfun$apply$8$$anonfun$3.apply(ScalaJSBundlerPlugin.scala:623)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$1.apply(Tracked.scala:253)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:267)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3$$anonfun$apply$4.apply(Tracked.scala:263)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:206)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:263)
	at sbt.FileFunction$$anonfun$cached$2$$anonfun$apply$3.apply(Tracked.scala:262)
	at sbt.Difference.apply(Tracked.scala:224)
	at sbt.Difference.apply(Tracked.scala:200)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:262)
	at sbt.FileFunction$$anonfun$cached$2.apply(Tracked.scala:260)
	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$testSettings$3$$anonfun$apply$8.apply(ScalaJSBundlerPlugin.scala:637)
	at scalajsbundler.sbtplugin.ScalaJSBundlerPlugin$$anonfun$testSettings$3$$anonfun$apply$8.apply(ScalaJSBundlerPlugin.scala:607)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### PR DESCRIPTION
**Pull request by jeroentervoorde**
Fixes #123

### CODE REVIEW

**Comment by jeroentervoorde** [comment]
I'll try (later...) I have no idea why the size changes. I wanted to ask you about that. My guess is that some stuff is running multithreaded which cause small changes in the output.

**Comment by dispalt** [comment]
Could it be webpack minor versions?

**Comment by julienrf** [comment]
test this please

**Comment by julienrf** [comment]
@dispalt yes, or more probably because of minor versions of uglify2.

**Comment by jeroentervoorde** [comment]
If it is a minor version update somewhere i guess npm-shrinkwrap would fix it. I can generate the npm-shrinkwrap.json and add it to webpackResources for my test (and maybe the static test too). 

I haven't used this before. Is adding npm-shrinkwrap.json to the working dir enough to have it picked up by npm/yarn?

**Comment by julienrf** [comment]
Honestly these change in the size of the minified bundle don’t bother me… I wouldn’t make the effort to maintain an npm-shrinkwrap configuration.

**Comment by jeroentervoorde** [comment]
Ok. I'll remove the size check in the sharedconfig test.

CI is failing now because of:

[info] [info] info If you think this is a bug, please open a bug report with the information provided in "C:\\Users\\appveyor\\AppData\\Local\\Temp\\1\\sbt_960e088e\\static\\target\\scala-2.11\\scalajs-bundler\\main\\yarn-error.log".
[info] [info] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[info] [error] error An unexpected error occurred: "https://registry.yarnpkg.com/source-map-loader: getaddrinfo EAI_AGAIN registry.yarnpkg.com:443".

**Comment by julienrf** [comment]
> Ok. I'll remove the size check in the sharedconfig test.

Actually this test is useful: it checks that the bundle has been minified, and therefore that the “prod” conf has effectively been picked by webpack. We could find a simpler way to check that, though :)

**Comment by jeroentervoorde** [comment]
How about checking if size < 200000 (instead of == 176366). The Unuglified output is 343959 so this should work.. (despite being an ugly hack)

**Comment by julienrf** [comment]
Yes, OK that would work too :)

**Comment by jeroentervoorde** [comment]
Done. I have to take a shower now :)

**Comment by julienrf** [comment]
test this please

**Pull request merged**
