### PR TITLE
Remove unnecessary assertions

### LINKED ISSUE #192: Webpack failed to create application bundle
Hi,
I am packaging some facade with scalajs-bundler. I added some config-files (to avoid using jquery): 
```js
module.exports = {
      "entry": {
    "demo-opt": [__dirname + "/bootstrapslider-opt.js"]
  },
  "output": {
    "path": __dirname,
    "filename": "[name]-bundle.js"
  },
    resolve: {
        alias: {
             "jquery": __dirname + "../../../resources/jquery-stub.js"
        }
    }
}
```
my built.sbt project is the following: 
```sbt
lazy val bootstrapslider = project.in(file("bootstrapslider")) enablePlugins (ScalaJSBundlerPlugin) settings(
  scalaJsDom,
  querki,
  npmDependencies in Compile += "bootstrap-slider" -> bootstrapSliderVersion,
  jsDependencies += ProvidedJS / "jquery-stub.js",
  webpackConfigFile := Some(baseDirectory.value / "jqueryConfig.config.js")
)
```

on a ```fullOptJS::wepack```, I get:

```sh
sbt:bootstrapslider> fullOptJS::webpack
[info] Writing scalajs.webpack.config.js
[info] Bundling the application with its NPM dependencies
[info] Hash: 8624608efa0a54f8ae83
[info] Version: webpack 3.5.5
[info] Time: 76ms
[info]              Asset     Size  Chunks             Chunk Names
[info] demo-opt-bundle.js  12.6 kB       0  [emitted]  demo-opt
[info]    [0] multi ./bootstrapslider-opt.js 28 bytes {0} [built]
[info]    [1] ./bootstrapslider-opt.js 9.27 kB {0} [built]
[info]    [2] (webpack)/buildin/global.js 509 bytes {0} [built]
[error] java.lang.AssertionError: assertion failed: Webpack failed to create application bundle
[error] 	at scala.Predef$.assert(Predef.scala:219)
[error] 	at scalajsbundler.Webpack$.bundle(Webpack.scala:152)
[error] 	at scalajsbundler.sbtplugin.WebpackTasks$.$anonfun$webpack$2(WebpackTasks.scala:45)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$1(FileFunction.scala:73)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$4(FileFunction.scala:147)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:293)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$3(FileFunction.scala:143)
[error] 	at sbt.util.Difference.apply(Tracked.scala:313)
[error] 	at sbt.util.Difference.apply(Tracked.scala:288)
[error] 	at sbt.util.FileFunction$.$anonfun$cached$2(FileFunction.scala:142)
[error] 	at scalajsbundler.sbtplugin.WebpackTasks$.$anonfun$webpack$1(WebpackTasks.scala:48)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:42)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:64)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:257)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:266)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:257)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:167)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:32)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (bootstrapslider/compile:fullOptJS::webpack) java.lang.AssertionError: assertion failed: Webpack failed to create application bundle
```
So everything seems to be fine until this puzzling exception. In the scalajs-bundler directory/main, the jquery-stub.js file is properly copied. 

Any idea ?

### PR DESCRIPTION
**Pull request by cquiroz**
Fixes #192

### CODE REVIEW

**Comment by cquiroz** [comment]
I tried this in some of my projects and it works in just some of them. In other cases it produces another exception down the line. I'll rework it.

**Comment by julienrf** [comment]
>  In other cases it produces another exception down the line

Can you elaborate?

**Comment by cquiroz** [comment]
in one particular project using a custom webpack config I get this:

```
[error] java.io.FileNotFoundException: /Users/cquiroz/Projects/scalajs-react-semantic-ui/demo/target/scala-2.12/scalajs-bundler/main/demo-opt-library.js (No such file or directory)
[error] 	at java.io.FileInputStream.open0(Native Method)
[error] 	at java.io.FileInputStream.open(FileInputStream.java:195)
[error] 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[error] 	at sbt.io.Using$.$anonfun$fileInputStream$1(Using.scala:88)
[error] 	at sbt.io.Using$$anon$2.openImpl(Using.scala:76)
[error] 	at sbt.io.OpenFile.open(Using.scala:43)
[error] 	at sbt.io.OpenFile.open$(Using.scala:39)
[error] 	at sbt.io.Using$$anon$2.open(Using.scala:75)
[error] 	at sbt.io.Using$$anon$2.open(Using.scala:75)
[error] 	at sbt.io.Using.apply(Using.scala:21)
[error] 	at sbt.io.IO$.readBytes(IO.scala:789)
[error] 	at scalajsbundler.util.JSBundler$.$anonfun$bundle$7(JSBundler.scala:103)
[error] 	at scalajsbundler.util.JSBundler$.$anonfun$bundle$7$adapted(JSBundler.scala:102)
```

I suspect this should be solved by finding exactly what webpack is producing rather than guessing it via naming conventions.

**Comment by cquiroz** [comment]
It seems you could do something like
`webpack --json > stats.json`
and parse the output to find out.

**Comment by julienrf** [comment]
Awesome, we should do that then!

**Comment by cquiroz** [comment]
i'm closing this as it needs a lot of rework

**Pull request closed without merging**
