### PR TITLE
update version on install instructions to 0.20.0

### PR DESCRIPTION
**Pull request by fiatjaf**
fixes https://github.com/scalacenter/scalajs-bundler/issues/402

### CODE REVIEW

**Comment by sjrd** [comment]
I could merge this, but it would be overwritten by a bot on the next merge on `main`. The actual source for this is at
https://github.com/scalacenter/scalajs-bundler/blob/b37024143b5a194de11a4395b367711eec2a3248/manual/src/ornate/index.md?plain=1#L11-L14
We should probably replace the dynamic `{{version}}`s by hard-corded ones.

**Comment by fiatjaf** [comment]
Why is the `{{version}}` printing the wrong value though? It would work if `{{version}}` corresponded to the latest release.

**Comment by sjrd** [comment]
I don't know. It's possible that the value of `{{version}}` comes from
https://github.com/scalacenter/scalajs-bundler/blob/d083e6df3fe2ac795ae16ba69696039bf85f85a3/manual/src/ornate.conf#L17
However, I don't know where the `${version}` comes from. :man_shrugging:

**Comment by fiatjaf** [comment]
ahahah, well, apparently it is a built-in thing from ornate, and there seems to be also a [`${tag}`](https://github.com/szeiger/ornate/blob/bfe49970a78bcc834e6555f0e5680aa70086c7ae/doc/ornate.conf#L35) value.

I should try to rebuild the pages using that and send a proper PR, but I'm just trying to learn the basic of basics of Scala here and all this sbt thing is imploding my head so I'll refrain from doing it now :P

**Pull request closed without merging**
