### PR TITLE
Remove ancient test

### PR DESCRIPTION
**Pull request by cquiroz**
I bet this can be safely removed

### CODE REVIEW

**Comment by easel** [comment]
LGTM

**Comment by cquiroz** [comment]
@julienrf Would it be ok to merge this?

**Comment by julienrf** [comment]
@cquiroz Yes, I didn’t have a look but I trust you guys :) In general, if you have write/merge rights you can merge after another maintainer has approved the PR.
Thank you both!

**Comment by cquiroz** [comment]
Thanks. I'll probably wait for #374 to be merged

**Review by sjrd — APPROVED** [review]
If you can rebase it on the latest master, just make sure the CI is fine, I'll merge even before my current PR. There are Windows issues over there that are blocking me atm.

**Pull request merged**
