### PR TITLE
[WIP] Support of Scala.js 1.0.0-RC2 instead of 1.0.0-RC1

### PR DESCRIPTION
**Pull request by raul782**

### CODE REVIEW

**Comment by FabioPinheiro** [comment]
The master branch is failing on the CIs 
https://travis-ci.org/scalacenter/scalajs-bundler/builds/630341659?utm_medium=notification&utm_source=github_status

**Comment by FabioPinheiro** [comment]
I public this locally for scalajs version "1.0.0-RC2" seems to be working on my demo project.
I would like to see this published even if it's only a snapshot.

@julienrf The master branch seems to be failing on the CIs

**Comment by sjrd** [comment]
> I would like to see this published even if it's only a snapshot.

Did you try using the latest published release (was it 0.16.0?) with RC2? Because it should just work out of the box already.

**Comment by FabioPinheiro** [comment]
@sjrdif I change to version 0.16.0 instead of my own local version
`addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.16.0")`
I get this error:
```
sbt:fmgp-scala-treejs> reload
[info] Loading settings for project global-plugins from plugins.sbt,metals.sbt ...
[info] Loading global plugins from /home/fabio/.sbt/1.0/plugins
[info] Loading settings for project fmgp-scala-treejs-build from plugins.sbt ...
[info] Loading project definition from /home/fabio/workspace/fmgp-scala-treejs/project
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] Loading settings for project fmgp-scala-treejs from build.sbt ...
[info] Set current project to fmgp-scala-treejs (in build file:/home/fabio/workspace/fmgp-scala-treejs/)
sbt:fmgp-scala-treejs> fastOptJS
[info] Compiling 2 Scala sources to /home/fabio/workspace/fmgp-scala-treejs/three/target/scala-2.13/classes ...
[info] Compiling 1 Scala source to /home/fabio/workspace/fmgp-scala-treejs/demo/target/scala-2.13/classes ...
[info] Fast optimizing /home/fabio/workspace/fmgp-scala-treejs/three/target/scala-2.13/scalajs-bundler/main/scala-threejs-fastopt.js
[info] Fast optimizing /home/fabio/workspace/fmgp-scala-treejs/demo/target/scala-2.13/scalajs-bundler/main/demo-fastopt.js
[error] stack trace is suppressed; run last demo / Compile / fastOptJS for the full output
[error] stack trace is suppressed; run last three / Compile / fastOptJS for the full output
[error] (demo / Compile / fastOptJS) org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.0-RC1 (supported up to: 1.0-RC2)
: org/scalajs/linker/runtime/RuntimeLong.sjsir
[error] You may need to upgrade the Scala.js sbt plugin to version 1.0-RC1 or later.
[error] (three / Compile / fastOptJS) org.scalajs.ir.IRVersionNotSupportedException: Failed to deserialize a file compiled with Scala.js 1.0-RC1 (supported up to: 1.0-RC2
): org/scalajs/linker/runtime/RuntimeLong.sjsir
[error] You may need to upgrade the Scala.js sbt plugin to version 1.0-RC1 or later.
[error] Total time: 11 s, completed Dec 28, 2019 8:56:50 PM
```

**Comment by FabioPinheiro** [comment]
I tested on Travis and got the same error @sjrd. 
https://travis-ci.com/FabioPinheiro/fmgp-threejs/builds/142553514

**Comment by sjrd** [comment]
Ah, then also add the following to your `project/plugins.sbt` file:
```scala
libraryDependencies += "org.scala-js" %% "scalajs-linker" %% "1.0.0-RC2"
```

**Comment by FabioPinheiro** [comment]
Thanks @sjrd 
That worked perfectly

**Comment by mikla** [comment]
Any help required here?

**Comment by julienrf** [comment]
I believe we can close this one since 1.0.0 is now released.

**Pull request closed without merging**
