### PR TITLE
Publish the sbt-scalajs-bundler before running the scripted tests for…

### PR DESCRIPTION
**Pull request by dispalt**
… sbt-web-scalajs-bundler

### CODE REVIEW

**Comment by julienrf** [comment]
Hi, can you give me more details on the problem that this PR solves?

**Comment by dispalt** [comment]
It forces `sbt-scalajs-bundler` plugin to be published locally (which is how scripted works) before running the sbt-web-scalajs-bundler scripted tests.  I ran into it when I was making changes to the core project and then wondering why the sbt-web subproject wasn't picking up the changes.

**Comment by julienrf** [comment]
test this please

**Comment by julienrf** [comment]
OK I see, this is great, thanks!

I will first fix the problem detected by the CI (which is not related to your PR) and then I will merge it.

**Comment by julienrf** [comment]
test this please

**Pull request merged**
