### PR TITLE
Drop AppVeyor

### PR DESCRIPTION
**Pull request by ptrdom**
With CI being already migrated to GitHub Actions, keeping AppVeyor seems unnecessary. Less CI scripts to maintain. Since GitHub Actions require approval for first time contributors and AppVeyor did not, maybe it would be good to reconsider loosening this rule for GitHub Actions in this repository.

### CODE REVIEW

**Comment by sjrd** [comment]
The point of the AppVeyor build is to test on Windows. If we remove AppVeyor, we must add a Windows build to the GitHub Actions CI.

**Comment by ptrdom** [comment]
GitHub has Windows machines available for running Actions, with matrix it is relatively easy to setup, I will add it to this PR.

**Comment by sjrd** [comment]
The Windows build doesn't seem to test anything. It completed in 1 minute without doing much of anything. By comparison, the Linux build takes more than 15 minutes.

**Comment by ptrdom** [comment]
Really strange. Posted in community about it - https://github.community/t/windows-runner-not-executing-sbt-commands/250507.

**Comment by armanbilge** [comment]
Note that olafurpg/setup-scala action is effectively deprecated. It might not be doing the right things.
- https://github.com/olafurpg/setup-scala/issues/49

**Comment by ptrdom** [comment]
@armanbilge You were right, many thanks! One test does fail, and the runner seems quite slow, but the same test fails on my Windows machine too. AppVeyor tests run on older WIndows Server version, so that must be related. Will look into that next.

**Comment by ptrdom** [comment]
Looks nasty:
```
Error: [error] (server / Compile / doc) java.net.URISyntaxException: Illegal character in path at index 53: [https://docs.oracle.com/en/java/javase/11/docs/api/C:\Users\runneradmin\AppData\Local\Coursier\cache\jvm\adopt@1.11.0-11\jmods\java.base/java/lang/Class.html](https://docs.oracle.com/en/java/javase/11/docs/api/C:/Users/runneradmin/AppData/Local/Coursier/cache/jvm/adopt@1.11.0-11/jmods/java.base/java/lang/Class.html)
```
https://github.com/scalacenter/scalajs-bundler/runs/6439309039?check_suite_focus=true#step:8:694

**Comment by ptrdom** [comment]
Looks related to https://github.com/scala/bug/issues/11955.

**Comment by ptrdom** [comment]
@sjrd Does this look mergeable to you?

**Comment by sjrd** [comment]
LGTM. Could you squash everything in a single commit with a clean commit message, please? Please also explain the change of Scala version in the test.

**Comment by ptrdom** [comment]
@sjrd Done!

**Review by sjrd — APPROVED** [review]

**Pull request merged**
